@echo off
title Titans Prime Ecosystem
echo 🚀 Lancement de l'IA Service...
start cmd /k "cd titans-ai-service && python start.py"
echo 🚀 Lancement du Bot Discord...
start cmd /k "cd titans-bot-core && npm run dev"
echo 🚀 Lancement de l'API Dashboard...
start cmd /k "cd titans-dashboard\server && node index.js"
echo 🚀 Lancement du Dashboard Prime (Vite)...
start cmd /k "cd titans-dashboard\client && npm run dev"
echo ✨ Ecosystem Titans Prime opérationnel.
